### PR TITLE
Fix exceptions.KeyError when trying to parse category name "Komödie"

### PR DESCRIPTION
**Pull request by andre-koehler**
...r some reason, category names are localized all of a sudden).

### CODE REVIEW

**Comment by learningit** [comment]
Didn't pull correctly, so I made the changes. Thanks for your help!

**Comment by learningit** [comment]
Actually, I just noticed in the US, the viewster domain has disappeared from the DNS. I'm not sure how you're able to make this work where you are.

**Comment by learningit** [comment]
Are you able to access the viewster.com domain? It has disappeared from DNS
registry here in US.

**Comment by andre-koehler** [comment]
You are right, this happened just now. I watched a show just an hour ago (in Germany).

**Comment by andre-koehler** [comment]
The IP if viewster.com was 80.74.132.62 yesterday, this can still be pinged right now.

**Comment by andre-koehler** [comment]
I was just working on adding support for subtitles in Anime, I hope I did not confuse the server with my requests.

**Pull request closed without merging**
